modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="gm"
version="1.0.0"
displayName="Gun mod"
credits="https://www.curseforge.com/minecraft/mc-mods/gun-mod-tl"
displayURL="https://www.curseforge.com/"
logoFile="logo.png"
authors="TL Studio"

[[dependencies.gm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




