modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="gm"
version="1.0.0"
displayName="gun mod"
credits="https://www.curseforge.com/minecraft/mc-mods/gun-mod-tl"
displayURL="https://www.curseforge.com/"
authors="TL Studio"

[[dependencies.gm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




